// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-space/DarkMatter.tsx": () => import("../components/mockups/hero-space/DarkMatter.tsx"),
  "./components/mockups/hero-space/NebulaDrift.tsx": () => import("../components/mockups/hero-space/NebulaDrift.tsx"),
  "./components/mockups/hero-space/ObsidianCosmos.tsx": () => import("../components/mockups/hero-space/ObsidianCosmos.tsx"),
  "./components/mockups/hero-space/RoyalNight.tsx": () => import("../components/mockups/hero-space/RoyalNight.tsx")
};
